# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: .\build.ps1
      
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: "client build"
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts\*-Client.zip
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: "server build"
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts\*-Server.zip
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error

      - name: Upload Container Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: "container build"
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts\*-Container.zip
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error